name: ESLint checker
on: [push]
uses: ninosaurus/eslint-check@v5.3.1
jobs: 
  Check ESLint rules:
  runs-on: ubuntu-latest
  
  steps:
  - name: Checkout code
  uses: actions/checkout@v4

  - name: Set up Node.js
  uses: actions/setup-node@v4

  - name: Install dependencies
  run: npm install

  - name: Run ESLint
  run: npx eslint --ext .js,.jsx,.vue,.ts,.tsx,.mts
