name: Cypress Tests

on: [push]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install
        
      - name: Run development server
        working-directory: ./Frontend
        run: npm run dev &
        
      - name: Run json server
        working-directory: ./Frontend
        run: npm run json-server &

      - name: Run Cypress tests
        working-directory: ./Frontend
        run: npm run cy:run
