name: ESLint checker
on: [push]

jobs:
  Check_ESLint_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        working-directory: ./Frontend 
        run: npm install

      - name: Run ESLint
        working-directory: ./Frontend
        run: npm run lint
