name: Prettier check

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Check code with Prettier
        working-directory: ./Frontend
        run: npm run p:check
